### ISSUE TITLE
Bits: Icon

### ISSUE THREAD

**Issue by luiguild** [atelier-saulx/ui#13]

**Comment by vassbence** [comment]
After exploring react-icons I'm not sure if it's the right fit for us, since as far as I know Sandor always creates his own icons in figma and does not use an off-the-self library. There was a similar situation in the previous UI lib too and we had a Figma export function which would spit out `.svg` files.

Regardless of how we acquire the raw svgs I think the more important question is how will they end up in the React bundle. Are we going to use something like [svgr](https://react-svgr.com/) which would allow us to import svg files or do we write the Figma export in such a way that it creates `.tsx` files where each icon is an individual React component already?

**Comment by vassbence** [comment]
https://www.figma.com/design/WmoUpRLIT4SQq5CY8XgfMG/%F0%9F%92%A0-Based-Component-Kit-(Do-not-use)?node-id=27-270&t=6wb8jzwtB3VbYAoW-0
