### ISSUE TITLE
Make logs look better

### ISSUE THREAD

**Issue by jimdebeer** [atelier-saulx/ui#85]
https://dribbble.com/shots/17783287-Plants-Facility-Activity-Log

something like this

**Comment by jimdebeer** [comment]
Functions
- query
- stream
- channel
- function
- app

subType: log, warn, error, "system"
https://based-cloud.pages.dev/dashboard/saulx/bidmeister/production/functions

**Comment by jimdebeer** [comment]
<img width="1455" alt="image" src="https://github.com/atelier-saulx/ui/assets/5682524/4bfc3963-cb54-4053-9661-167d493f8c62">

**Comment by maartensaulx** [comment]
https://www.figma.com/file/6QyAOyFMSDuz7DU4LjyIQb/Functions-%2F-Logs?type=design&node-id=711%3A18975&mode=design&t=tO1JGlxjZZgxaAff-1
I've discussed this a bit with Jim and we think it's a cool idea to add status indicators to the logs. 
Error (red), Warning (yellow), System (blue), Log (grey).
Aside from that design i've made is kinda a mix between the current implementation and the version you made.

**Comment by maartensaulx** [comment]
I've also removed the hover state. I think it's nice if the 'preview title' is clickable to expand and collapse the log. The actual log itself shouldn't be clickable imo since I guess sometimes user would want to copy paste / select portion of the log. Maybe also nice to add that, being able to select and copy/paste the text in the log.
Also let's add the cursor for clickable elements when something is clickable
by the way the content of my design is not correct in any way, it's just dummy content I took since in general I have no idea what's going on with the logs and what is what 😄

**Comment by maartensaulx** [comment]
https://github.com/atelier-saulx/ui/assets/67953561/b94d8ee0-c45c-476b-a9b7-2f6225cdfce7

**Comment by jimdebeer** [comment]
i have to add some extra parsing for the where the logs are set
(how to display objects, etc)

lmk when done @cowboybeer

**Comment by cowboybeer** [comment]
Parse object to show different style
